import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/recipe.dart';

class RecipeService {
  final CollectionReference _recipesRef =
      FirebaseFirestore.instance.collection('recipes');


  // Données fictives pour les recettes
  final List<Recipe> _mockRecipes = [
    Recipe(
      id: '1',
      title: 'Jollof Rice (Riz Jollof)',
      shortDescription: 'Riz épicé nigerian, plat national d\'Afrique de l\'Ouest.',
      fullDescription: 'Le Jollof Rice est un plat traditionnel d\'Afrique de l\'Ouest, particulièrement populaire au Nigeria et au Ghana. Ce riz parfumé est cuit avec une sauce tomate riche en épices, accompagné de légumes et de protéines. Préparation: 20 min | Cuisson: 45 min | Difficulté: Moyenne | Portions: 6',
      imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      price: 8.99,
      currency: 'USD',
      likes: 245,
      rating: 4.5,
      ingredients: [
        '400g de riz basmati ou riz parfumé',
        '6 tomates mûres',
        '2 oignons rouges',
        '3 gousses d\'ail',
        '2 cuillères à soupe de concentré de tomate',
        '1 poivron rouge',
        '1 poivron vert',
        '2 cuillères à café de curry en poudre',
        '1 cuillère à café de thym',
        '2 cubes de bouillon de poulet',
        'Huile de palme ou huile végétale',
        'Sel et poivre',
        'Persil frais pour garnir'
      ],
      instructions: [
        'Éplucher et hacher les oignons, l\'ail et les poivrons.',
        'Faire chauffer l\'huile dans une grande casserole et faire revenir les oignons jusqu\'à ce qu\'ils soient translucides.',
        'Ajouter l\'ail, les poivrons et les épices. Faire revenir 2 minutes.',
        'Incorporer les tomates concassées et le concentré de tomate.',
        'Ajouter les cubes de bouillon émiettés et 500ml d\'eau.',
        'Porter à ébullition puis ajouter le riz rincé.',
        'Baisser le feu, couvrir et laisser cuire 25-30 minutes jusqu\'à absorption complète du liquide.',
        'Laisser reposer 5 minutes à couvert, puis servir garni de persil.'
      ],
    ),
    Recipe(
      id: '2',
      title: 'Tagine Marocain',
      shortDescription: 'Ragoût marocain parfumé aux épices orientales.',
      fullDescription: 'Le tagine est un plat traditionnel marocain cuit lentement dans un plat conique en terre cuite. Cette version aux pruneaux et amandes combine douceur et saveurs orientales. Préparation: 30 min | Cuisson: 2h | Difficulté: Moyenne | Portions: 4',
      imageUrl: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400',
      price: 12.50,
      currency: 'USD',
      likes: 189,
      rating: 4.2,
      ingredients: [
        '1kg d\'agneau coupé en morceaux',
        '200g de pruneaux dénoyautés',
        '100g d\'amandes grillées',
        '2 oignons',
        '3 gousses d\'ail',
        '1 cuillère à café de gingembre en poudre',
        '1 cuillère à café de cannelle',
        '1/2 cuillère à café de curcuma',
        '1/2 cuillère à café de safran',
        '2 cuillères à soupe de miel',
        'Huile d\'olive',
        'Sel et poivre',
        'Coriandre fraîche'
      ],
      instructions: [
        'Faire mariner l\'agneau avec les épices, l\'ail écrasé et l\'huile d\'olive pendant 1 heure.',
        'Dans un tagine ou une cocotte, faire revenir les oignons émincés.',
        'Ajouter l\'agneau mariné et faire dorer sur toutes les faces.',
        'Incorporer les pruneaux et les amandes.',
        'Ajouter 300ml d\'eau et le miel.',
        'Couvrir et laisser mijoter à feu doux pendant 1h30.',
        'Vérifier la cuisson de la viande et rectifier l\'assaisonnement.',
        'Servir chaud garni de coriandre fraîche avec du couscous.'
      ],
    ),
    Recipe(
      id: '3',
      title: 'Bobotie Sud-Africain',
      shortDescription: 'Gratin épicé à la viande hachée, spécialité sud-africaine.',
      fullDescription: 'Le bobotie est un plat traditionnel sud-africain d\'origine malaise. C\'est un gratin de viande hachée aux épices, recouvert d\'un œuf battu, qui marie les saveurs orientales et africaines. Préparation: 25 min | Cuisson: 45 min | Difficulté: Facile | Portions: 6',
      imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      price: 9.75,
      currency: 'USD',
      likes: 312,
      rating: 4.7,
      ingredients: [
        '800g de bœuf haché',
        '2 oignons',
        '2 tranches de pain de mie',
        '250ml de lait',
        '2 œufs',
        '100g d\'abricots secs',
        '50g de raisins secs',
        '2 cuillères à soupe de curry en poudre',
        '1 cuillère à café de curcuma',
        '1 cuillère à soupe de chutney à la mangue',
        '2 feuilles de laurier',
        'Sel et poivre',
        'Huile pour la cuisson'
      ],
      instructions: [
        'Préchauffer le four à 180°C.',
        'Faire tremper le pain dans le lait.',
        'Faire revenir les oignons hachés dans l\'huile.',
        'Ajouter le bœuf haché et faire cuire jusqu\'à ce qu\'il perde sa couleur rose.',
        'Incorporer le curry, le curcuma, le chutney, les abricots et raisins secs.',
        'Essorer le pain et l\'émietter dans la préparation.',
        'Ajouter les feuilles de laurier et assaisonner.',
        'Verser dans un plat allant au four.',
        'Battre les œufs avec le lait restant et verser sur la préparation.',
        'Enfourner pour 30 minutes jusqu\'à ce que le dessus soit doré.'
      ],
    ),
    Recipe(
      id: '4',
      title: 'Injera Ethiopien',
      shortDescription: 'Crêpe spongieuse à base de teff, base de la cuisine éthiopienne.',
      fullDescription: 'L\'injera est la galette traditionnelle éthiopienne faite à base de farine de teff. Légèrement aigre, elle sert de base aux plats éthiopiens et permet de saisir la nourriture avec les doigts. Préparation: 10 min | Repos: 24h | Cuisson: 15 min | Difficulté: Moyenne | Portions: 4',
      imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      price: 6.25,
      currency: 'USD',
      likes: 156,
      rating: 4.4,
      ingredients: [
        '300g de farine de teff',
        '500ml d\'eau tiède',
        '1 sachet de levure de boulanger',
        '1/2 cuillère à café de sel',
        'Huile pour la cuisson'
      ],
      instructions: [
        'Mélanger la farine de teff avec l\'eau tiède pour obtenir une pâte lisse.',
        'Ajouter la levure et le sel.',
        'Couvrir et laisser fermenter 24 heures à température ambiante.',
        'Le lendemain, remuer la pâte (elle doit être légèrement gazeuse).',
        'Faire chauffer une poêle antiadhésive légèrement huilée.',
        'Verser une louche de pâte et l\'étaler en cercle.',
        'Cuire 2-3 minutes jusqu\'à ce que des bulles apparaissent.',
        'Retourner et cuire 1 minute supplémentaire.',
        'Empiler les injeras et garder au chaud.',
        'Servir avec des plats éthiopiens comme le doro wat.'
      ],
    ),
    Recipe(
      id: '5',
      title: 'Poulet Yassa Sénégalais',
      shortDescription: 'Poulet mariné au citron et aux oignons, spécialité sénégalaise.',
      fullDescription: 'Le poulet yassa est un plat traditionnel sénégalais. Le poulet est mariné dans une sauce au citron et aux oignons, puis grillé ou poêlé pour un résultat juteux et parfumé. Préparation: 30 min | Marinage: 2h | Cuisson: 40 min | Difficulté: Facile | Portions: 4',
      imageUrl: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400',
      price: 100.0,
      currency: 'CDF',
      likes: 198,
      rating: 4.3,
      ingredients: [
        '1 poulet entier coupé en morceaux',
        '6 oignons moyens',
        '4 citrons verts',
        '4 gousses d\'ail',
        '2 cuillères à soupe de moutarde',
        '2 cuillères à soupe d\'huile d\'arachide',
        '2 cubes de bouillon de volaille',
        '1 piment (optionnel)',
        'Sel et poivre',
        'Persil ou ciboulette pour garnir'
      ],
      instructions: [
        'Pressez le jus des citrons et émincez finement les oignons.',
        'Dans un grand saladier, mélanger le jus de citron, les oignons, l\'ail écrasé, la moutarde et l\'huile.',
        'Ajouter les morceaux de poulet et bien mélanger pour enrober.',
        'Couvrir et laisser mariner au réfrigérateur minimum 2 heures.',
        'Dans une grande poêle ou un wok, faire chauffer un peu d\'huile.',
        'Faire revenir les morceaux de poulet avec leur marinade.',
        'Ajouter les cubes de bouillon émiettés et un verre d\'eau.',
        'Laisser mijoter 30-35 minutes jusqu\'à ce que le poulet soit tendre.',
        'Rectifier l\'assaisonnement et servir avec du riz blanc.'
      ],
    ),
    Recipe(
      id: '6',
      title: 'Kachumbari Tanzanien',
      shortDescription: 'Salade fraîche tanzanienne aux tomates et oignons.',
      fullDescription: 'Le kachumbari est une salade fraîche traditionnelle tanzanienne. Cette salade croquante combine tomates, oignons et coriandre avec une vinaigrette au vinaigre et à l\'huile. Préparation: 15 min | Repos: 10 min | Difficulté: Facile | Portions: 4',
      imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
      price: 100.0,
      currency: 'CDF',
      likes: 187,
      rating: 4.4,
      ingredients: [
        '4 tomates mûres',
        '2 oignons rouges moyens',
        '1 poivron vert',
        '1 bouquet de coriandre fraîche',
        'Jus de 2 citrons verts',
        '3 cuillères à soupe d\'huile d\'olive',
        'Sel et poivre noir',
        '1 piment frais (optionnel)'
      ],
      instructions: [
        'Laver et couper les tomates en petits dés.',
        'Éplucher et émincer finement les oignons.',
        'Couper le poivron en petits dés.',
        'Hacher grossièrement la coriandre.',
        'Dans un saladier, mélanger tomates, oignons et poivron.',
        'Préparer la vinaigrette avec jus de citron, huile, sel et poivre.',
        'Verser la vinaigrette sur les légumes.',
        'Ajouter la coriandre et mélanger délicatement.',
        'Laisser reposer 10 minutes au réfrigérateur.',
        'Servir frais comme accompagnement.'
      ],
    ),
    Recipe(
      id: '7',
      title: 'Couscous Royal Marocain',
      shortDescription: 'Plat complet marocain aux sept légumes.',
      fullDescription: 'Le couscous royal est un plat marocain traditionnel composé de semoule fine accompagnée d\'un tajine aux sept légumes et de viande d\'agneau parfumée aux épices orientales. Préparation: 1h | Cuisson: 2h30 | Difficulté: Difficile | Portions: 8',
      imageUrl: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400',
      price: 18.99,
      currency: 'USD',
      likes: 312,
      rating: 4.8,
      ingredients: [
        '1kg de semoule fine de couscous',
        '1kg d\'agneau (épaule et collier)',
        '4 carottes',
        '4 navets',
        '4 courgettes',
        '2 poivrons (rouge et vert)',
        '400g de pois chiches cuits',
        '4 tomates',
        '4 oignons',
        'Ras-el-hanout, safran, cumin',
        'Coriandre, persil',
        'Huile d\'olive, beurre',
        'Bouillon de légumes'
      ],
      instructions: [
        'Couper l\'agneau en morceaux et le faire revenir dans l\'huile.',
        'Ajouter oignons émincés, ail et épices. Faire dorer.',
        'Incorporer tomates concassées et bouillon.',
        'Ajouter pois chiches et laisser mijoter 30 minutes.',
        'Ajouter carottes et navets coupés en gros morceaux.',
        'Après 30 minutes, ajouter courgettes et poivrons.',
        'Préparer la semoule selon les instructions (vapeur).',
        'Servir la semoule avec le tajine et légumes.',
        'Garnir de coriandre fraîche et servir immédiatement.'
      ],
    ),
    Recipe(
      id: '8',
      title: 'Sambusa Somaliens',
      shortDescription: 'Samosas africains farcis à la viande épicée.',
      fullDescription: 'Les sambusas sont des samosas traditionnels somaliens. Ces triangles croustillants sont farcis d\'un mélange de viande hachée épicée et servis avec une sauce piquante. Préparation: 45 min | Cuisson: 20 min | Difficulté: Moyenne | Portions: 6',
      imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      price: 100.0,
      currency: 'CDF',
      likes: 234,
      rating: 4.5,
      ingredients: [
        '500g de bœuf haché',
        '2 oignons finement hachés',
        '2 gousses d\'ail écrasées',
        '1 cm de gingembre frais râpé',
        'Feuilles de brick ou pâte à sambusa',
        'Épices : cumin, coriandre, cardamome',
        'Piment en poudre, curcuma',
        'Huile pour friture',
        'Sel et poivre',
        'Coriandre fraîche'
      ],
      instructions: [
        'Faire revenir oignons, ail et gingembre dans l\'huile.',
        'Ajouter la viande hachée et faire dorer.',
        'Incorporer toutes les épices et laisser cuire 10 minutes.',
        'Ajouter coriandre hachée et laisser refroidir.',
        'Couper les feuilles de brick en triangles.',
        'Déposer une cuillère de farce au centre de chaque triangle.',
        'Plier en triangle et sceller les bords avec de l\'eau.',
        'Frire dans l\'huile chaude jusqu\'à dorure.',
        'Égoutter sur papier absorbant et servir chaud.'
      ],
    ),
    Recipe(
      id: '9',
      title: 'Doro Wat Ethiopien',
      shortDescription: 'Poulet épicé éthiopien au berbéré.',
      fullDescription: 'Le doro wat est le plat national éthiopien. Ce poulet mijoté dans une sauce épicée au berbéré est servi avec des œufs durs et de l\'injera, le pain traditionnel éthiopien. Préparation: 30 min | Marinage: 1h | Cuisson: 1h | Difficulté: Moyenne | Portions: 6',
      imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
      price: 14.50,
      currency: 'USD',
      likes: 278,
      rating: 4.7,
      ingredients: [
        '1 poulet entier coupé en morceaux',
        '6 œufs durs',
        '4 oignons finement hachés',
        '4 gousses d\'ail écrasées',
        '2 cm de gingembre frais râpé',
        'Épice berbéré (ou paprika, piment, cumin)',
        '2 cuillères à soupe de nitr kébbé (beurre clarifié)',
        'Bouillon de poulet',
        'Sel et poivre',
        'Coriandre pour garnir'
      ],
      instructions: [
        'Mariner le poulet avec berbéré, ail et gingembre 1 heure.',
        'Faire revenir les oignons dans le nitr kébbé jusqu\'à caramelisation.',
        'Ajouter le poulet mariné et faire dorer.',
        'Incorporer le bouillon et laisser mijoter 45 minutes.',
        'Ajouter les œufs durs 10 minutes avant la fin.',
        'Ajuster l\'assaisonnement.',
        'Servir avec de l\'injera et garnir de coriandre.'
      ],
    ),
    Recipe(
      id: '10',
      title: 'Chakchouka Tunisienne',
      shortDescription: 'Œufs à la sauce tomate épicée tunisienne.',
      fullDescription: 'La chakchouka est un plat tunisien traditionnel. Des œufs pochés dans une sauce tomate riche en épices, accompagnés de pain frais. Préparation: 15 min | Cuisson: 25 min | Difficulté: Facile | Portions: 4',
      imageUrl: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400',
      price: 100.0,
      currency: 'CDF',
      likes: 245,
      rating: 4.6,
      ingredients: [
        '6 œufs frais',
        '4 tomates mûres',
        '2 poivrons (rouge et vert)',
        '2 oignons moyens',
        '3 gousses d\'ail',
        'Harissa (pâte de piment tunisienne)',
        'Cumin, paprika, carvi',
        'Huile d\'olive',
        'Sel et poivre',
        'Persil frais pour garnir'
      ],
      instructions: [
        'Éplucher et hacher oignons et ail.',
        'Couper tomates et poivrons en dés.',
        'Faire chauffer l\'huile et faire revenir oignons.',
        'Ajouter ail, poivrons et épices. Cuire 5 minutes.',
        'Incorporer les tomates et harissa. Laisser mijoter 15 minutes.',
        'Casser les œufs un à un dans la sauce.',
        'Couvrir et cuire jusqu\'à ce que les blancs soient pris.',
        'Garnir de persil et servir avec du pain.'
      ],
    ),
    Recipe(
      id: '11',
      title: 'Matoke Ougandais',
      shortDescription: 'Bananes plantains mijotées à l\'ougandaise.',
      fullDescription: 'Le matoke est un plat traditionnel ougandais. Des bananes plantains vertes sont cuites lentement dans une sauce aux tomates et oignons, accompagnées de viande ou servies seules. Préparation: 20 min | Cuisson: 40 min | Difficulté: Moyenne | Portions: 6',
      imageUrl: 'https://images.unsplash.com/photo-1571771019784-3ff35f4f4277?w=400',
      price: 8.75,
      currency: 'USD',
      likes: 198,
      rating: 4.3,
      ingredients: [
        '12 bananes plantains vertes',
        '500g de bœuf haché (optionnel)',
        '4 tomates',
        '2 oignons',
        '2 gousses d\'ail',
        '2 cuillères à soupe d\'huile de palme',
        'Bouillon de légumes',
        'Sel, poivre, piment',
        'Coriandre fraîche'
      ],
      instructions: [
        'Éplucher les bananes plantains et les couper en rondelles.',
        'Faire revenir oignons et ail dans l\'huile.',
        'Ajouter la viande si utilisée et faire dorer.',
        'Incorporer tomates concassées et épices.',
        'Ajouter les bananes et couvrir de bouillon.',
        'Laisser mijoter 30-35 minutes jusqu\'à tendreté.',
        'Écraser légèrement les bananes avec une fourchette.',
        'Garnir de coriandre et servir chaud.'
      ],
    ),
    Recipe(
      id: '12',
      title: 'Pastilla Marocaine',
      shortDescription: 'Feuilleté royal marocain au poulet et amandes.',
      fullDescription: 'La pastilla est une spécialité marocaine royale. Ce feuilleté croustillant combine poulet confit, amandes grillées et œufs dans une pâte filo parfumée à la cannelle. Préparation: 1h | Cuisson: 45 min | Difficulté: Difficile | Portions: 8',
      imageUrl: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400',
      price: 100.0,
      currency: 'CDF',
      likes: 267,
      rating: 4.8,
      ingredients: [
        '1 poulet entier',
        '300g d\'amandes grillées',
        '8 œufs',
        'Pâte filo (ou warqa)',
        '4 oignons',
        'Safran, cannelle, gingembre',
        'Beurre clarifié',
        'Sucre glace et cannelle pour saupoudrer',
        'Sel et poivre'
      ],
      instructions: [
        'Faire cuire le poulet avec oignons et épices.',
        'Effilocher la chair et réserver le bouillon.',
        'Battre les œufs et les cuire en omelette avec le bouillon.',
        'Concasser les amandes.',
        'Beurrer un moule et disposer les feuilles de filo.',
        'Alterner couches de poulet, œufs et amandes.',
        'Plier les bords et badigeonner de beurre.',
        'Enfourner à 180°C pendant 30 minutes.',
        'Saupoudrer de sucre et cannelle avant de servir.'
      ],
    ),
    Recipe(
      id: '13',
      title: 'Achu Soup Camerounais',
      shortDescription: 'Soupe camerounaise aux feuilles de manioc.',
      fullDescription: 'L\'achu soup est une soupe traditionnelle camerounaise. Des feuilles de manioc mijotent avec de la viande et des épices dans une sauce riche et savoureuse. Préparation: 30 min | Cuisson: 1h30 | Difficulté: Moyenne | Portions: 6',
      imageUrl: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=400',
      price: 12.25,
      currency: 'USD',
      likes: 189,
      rating: 4.4,
      ingredients: [
        '1kg de feuilles de manioc (achu)',
        '500g de bœuf ou poulet',
        '4 tomates',
        '2 oignons',
        '3 gousses d\'ail',
        'Piment, poivre noir',
        'Huile de palme',
        'Bouillon de viande',
        'Sel et épices locales'
      ],
      instructions: [
        'Laver et hacher finement les feuilles de manioc.',
        'Faire cuire la viande avec oignons et ail.',
        'Ajouter tomates concassées et épices.',
        'Incorporer les feuilles de manioc.',
        'Couvrir de bouillon et laisser mijoter 1 heure.',
        'Ajouter huile de palme et piment selon goût.',
        'Laisser réduire légèrement.',
        'Servir chaud avec du foufou ou du riz.'
      ],
    ),
    Recipe(
      id: '14',
      title: 'Bunny Chow Sud-Africain',
      shortDescription: 'Pain farci sud-africain au curry.',
      fullDescription: 'Le bunny chow est un plat traditionnel sud-africain d\'origine indienne. Du pain frais est évidé et farci d\'un curry de légumes épicé, créant un repas complet et savoureux. Préparation: 20 min | Cuisson: 35 min | Difficulté: Moyenne | Portions: 4',
      imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      price: 100.0,
      currency: 'CDF',
      likes: 223,
      rating: 4.5,
      ingredients: [
        '4 pains ronds frais (bunny loaf)',
        '500g de pommes de terre',
        '2 carottes',
        '200g de pois chiches',
        '2 oignons',
        '3 gousses d\'ail',
        'Curry en poudre, curcuma, cumin',
        'Tomates, piment',
        'Huile, sel',
        'Coriandre fraîche'
      ],
      instructions: [
        'Évider les pains en gardant le couvercle.',
        'Couper légumes en dés.',
        'Faire revenir oignons et ail dans l\'huile.',
        'Ajouter épices et légumes. Cuire 10 minutes.',
        'Incorporer pois chiches et tomates.',
        'Ajouter eau et laisser mijoter 20 minutes.',
        'Farcir les pains avec le curry.',
        'Garnir de coriandre et servir immédiatement.'
      ],
    ),
    Recipe(
      id: '15',
      title: 'Muamba de Galinha Angolais',
      shortDescription: 'Poulet angolais au palmiste et arachides.',
      fullDescription: 'Le muamba de galinha est le plat national angolais. Du poulet mijoté dans une sauce crémeuse à base de palmiste et d\'arachides, servi avec du riz ou du funje. Préparation: 25 min | Cuisson: 1h | Difficulté: Moyenne | Portions: 6',
      imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
      price: 16.99,
      currency: 'USD',
      likes: 245,
      rating: 4.6,
      ingredients: [
        '1 poulet entier coupé en morceaux',
        '200g de pâte de palmiste',
        '100g de beurre d\'arachide',
        '4 tomates',
        '2 oignons',
        '3 gousses d\'ail',
        'Piment, gingembre',
        'Huile de palme',
        'Bouillon de poulet',
        'Sel et poivre'
      ],
      instructions: [
        'Faire revenir oignons, ail et gingembre.',
        'Ajouter poulet et faire dorer.',
        'Incorporer tomates concassées.',
        'Diluer pâte de palmiste dans le bouillon.',
        'Ajouter au poulet et laisser mijoter 30 minutes.',
        'Incorporer beurre d\'arachide.',
        'Ajouter piment et huile de palme.',
        'Laisser réduire 20 minutes.',
        'Servir avec du riz ou funje.'
      ],
    ),
    Recipe(
      id: '16',
      title: 'Koki Congolais',
      shortDescription: 'Gâteau de haricots congolais aux épinards.',
      fullDescription: 'Le koki est un plat traditionnel congolais. Des haricots noirs cuits avec des épinards et des épices, enveloppés dans des feuilles de bananier et cuits à la vapeur. Préparation: 30 min | Cuisson: 45 min | Difficulté: Moyenne | Portions: 6',
      imageUrl: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400',
      price: 100.0,
      currency: 'CDF',
      likes: 178,
      rating: 4.3,
      ingredients: [
        '500g de haricots noirs',
        '200g d\'épinards frais',
        '2 oignons',
        '2 gousses d\'ail',
        'Piment, poivre',
        'Huile de palme',
        'Feuilles de bananier',
        'Sel et épices locales'
      ],
      instructions: [
        'Faire tremper les haricots overnight.',
        'Cuire les haricots jusqu\'à tendreté.',
        'Hacher épinards, oignons et ail.',
        'Mélanger haricots avec légumes et épices.',
        'Ajouter huile de palme.',
        'Envelopper dans feuilles de bananier.',
        'Cuire à la vapeur 30 minutes.',
        'Servir chaud comme accompagnement.'
      ],
    ),
    Recipe(
      id: '17',
      title: 'Domoda Gambien',
      shortDescription: 'Ragoût gambien aux cacahuètes et légumes.',
      fullDescription: 'Le domoda est un ragoût traditionnel gambien. De la viande mijote avec des légumes et une sauce crémeuse aux cacahuètes, accompagnée de riz blanc. Préparation: 20 min | Cuisson: 1h30 | Difficulté: Moyenne | Portions: 6',
      imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      price: 11.75,
      currency: 'USD',
      likes: 201,
      rating: 4.4,
      ingredients: [
        '1kg de bœuf ou mouton',
        '200g de beurre de cacahuète',
        '4 tomates',
        '2 oignons',
        '3 gousses d\'ail',
        '2 carottes',
        'Piment, thym',
        'Huile végétale',
        'Bouillon de viande',
        'Sel et poivre'
      ],
      instructions: [
        'Couper la viande en cubes.',
        'Faire revenir oignons et ail.',
        'Ajouter viande et faire dorer.',
        'Incorporer tomates et carottes.',
        'Ajouter bouillon et épices.',
        'Laisser mijoter 1 heure.',
        'Incorporer beurre de cacahuète dilué.',
        'Laisser réduire 20 minutes.',
        'Servir avec du riz blanc.'
      ],
    ),
    Recipe(
      id: '18',
      title: 'Jambalaya Louisianais',
      shortDescription: 'Riz créole africain aux fruits de mer.',
      fullDescription: 'Le jambalaya est un plat créole louisianais d\'influence africaine. Du riz cuit avec des fruits de mer, saucisses et légumes dans un bouillon épicé. Préparation: 25 min | Cuisson: 45 min | Difficulté: Moyenne | Portions: 8',
      imageUrl: 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?w=400',
      price: 100.0,
      currency: 'CDF',
      likes: 289,
      rating: 4.7,
      ingredients: [
        '400g de riz long',
        '300g de crevettes',
        '300g de saucisses andouille',
        '200g de poulet',
        '1 poivron, 2 branches de céleri',
        '1 oignon, 3 gousses d\'ail',
        'Bouillon de poulet',
        'Paprika, thym, cayenne',
        'Huile d\'olive',
        'Persil frais'
      ],
      instructions: [
        'Faire revenir saucisses et poulet.',
        'Ajouter légumes et ail.',
        'Incorporer riz et épices.',
        'Ajouter bouillon et porter à ébullition.',
        'Ajouter crevettes et laisser cuire 20 minutes.',
        'Couvrir et laisser reposer 10 minutes.',
        'Garnir de persil et servir.'
      ],
    ),
    Recipe(
      id: '19',
      title: 'Feijoada Brésilienne',
      shortDescription: 'Ragoût brésilien aux haricots noirs africains.',
      fullDescription: 'La feijoada est le plat national brésilien d\'origine africaine. Des haricots noirs mijotent avec diverses viandes fumées et saucisses, servis avec du riz et des oranges. Préparation: 30 min | Trempage: 12h | Cuisson: 3h | Difficulté: Moyenne | Portions: 8',
      imageUrl: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400',
      price: 17.50,
      currency: 'USD',
      likes: 312,
      rating: 4.8,
      ingredients: [
        '1kg de haricots noirs',
        '500g de viandes mélangées (oreille, queue, etc.)',
        '300g de saucisses',
        '200g de bacon',
        '2 oignons, 4 gousses d\'ail',
        'Laurier, thym',
        'Huile d\'olive',
        'Riz blanc pour servir',
        'Oranges, farofa'
      ],
      instructions: [
        'Tremper haricots overnight.',
        'Faire revenir viandes et saucisses.',
        'Ajouter oignons et ail.',
        'Incorporer haricots égouttés.',
        'Couvrir d\'eau et ajouter herbes.',
        'Laisser mijoter 3 heures.',
        'Servir avec riz, oranges et farofa.'
      ],
    ),
    Recipe(
      id: '20',
      title: 'Acarajé Brésilien',
      shortDescription: 'Beignets africains aux crevettes d\'origine yoruba.',
      fullDescription: 'L\'acarajé est un beignet brésilien d\'origine africaine yoruba. Des pois noirs frits farcis de crevettes et de vatapá, servis avec une sauce piquante. Préparation: 30 min | Trempage: 8h | Cuisson: 20 min | Difficulté: Moyenne | Portions: 6',
      imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      price: 100.0,
      currency: 'CDF',
      likes: 234,
      rating: 4.5,
      ingredients: [
        '500g de pois noirs',
        '200g de crevettes',
        '2 oignons',
        'Vatapá (pâte de cacahuètes)',
        'Huile de palme pour friture',
        'Sel, piment',
        'Caruru (légumes)',
        'Coriandre'
      ],
      instructions: [
        'Tremper pois noirs 8 heures.',
        'Mixer avec oignons et sel.',
        'Façonner en boules.',
        'Frire dans huile chaude.',
        'Préparer farce crevettes.',
        'Ouvrir beignets et farcir.',
        'Servir avec sauces.'
      ],
    ),
    Recipe(
      id: '21',
      title: 'Mafé Sénégalais',
      shortDescription: 'Ragoût sénégalais aux cacahuètes et légumes.',
      fullDescription: 'Le mafé est un ragoût traditionnel sénégalais. De la viande mijote dans une sauce crémeuse aux cacahuètes avec des légumes, servi avec du riz blanc. Préparation: 20 min | Cuisson: 1h30 | Difficulté: Moyenne | Portions: 6',
      imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
      price: 13.99,
      currency: 'USD',
      likes: 267,
      rating: 4.6,
      ingredients: [
        '1kg de bœuf ou mouton',
        '300g de beurre de cacahuète',
        '4 tomates',
        '2 oignons',
        '3 gousses d\'ail',
        '2 carottes, 2 patates douces',
        'Piment, thym, laurier',
        'Huile végétale',
        'Bouillon de viande',
        'Sel et poivre'
      ],
      instructions: [
        'Couper viande en cubes.',
        'Faire revenir oignons et ail.',
        'Ajouter viande et dorer.',
        'Incorporer légumes et tomates.',
        'Ajouter bouillon et épices.',
        'Laisser mijoter 1 heure.',
        'Incorporer beurre de cacahuète.',
        'Laisser réduire 20 minutes.',
        'Servir avec riz blanc.'
      ],
    ),
    Recipe(
      id: '22',
      title: 'Saka-Saka Congolais',
      shortDescription: 'Feuilles de manioc mijotées congolaises.',
      fullDescription: 'Le saka-saka est un plat traditionnel congolais. Des feuilles de manioc mijotent avec du poisson séché ou de la viande dans une sauce savoureuse. Préparation: 30 min | Cuisson: 45 min | Difficulté: Moyenne | Portions: 6',
      imageUrl: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=400',
      price: 100.0,
      currency: 'CDF',
      likes: 198,
      rating: 4.4,
      ingredients: [
        '1kg de feuilles de manioc',
        '300g de poisson séché ou bœuf',
        '4 tomates',
        '2 oignons',
        '3 gousses d\'ail',
        'Piment, poivre',
        'Huile de palme',
        'Bouillon',
        'Sel et épices'
      ],
      instructions: [
        'Laver et hacher feuilles.',
        'Faire revenir oignons et ail.',
        'Ajouter poisson/bœuf.',
        'Incorporer tomates.',
        'Ajouter feuilles de manioc.',
        'Couvrir de bouillon.',
        'Laisser mijoter 35 minutes.',
        'Servir avec foufou.'
      ],
    ),
    Recipe(
      id: '23',
      title: 'Poulet Moambe Congolais',
      shortDescription: 'Poulet congolais au palmiste traditionnel.',
      fullDescription: 'Le poulet moambe est le plat national congolais. Du poulet mijoté dans une sauce riche à base de palmiste, servi avec du riz ou du foufou. Préparation: 20 min | Cuisson: 1h | Difficulté: Moyenne | Portions: 6',
      imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
      price: 15.25,
      currency: 'USD',
      likes: 278,
      rating: 4.7,
      ingredients: [
        '1 poulet entier coupé',
        '300g de pâte de palmiste',
        '4 tomates',
        '2 oignons',
        '3 gousses d\'ail',
        'Piment, gingembre',
        'Huile de palme',
        'Bouillon de poulet',
        'Sel et poivre'
      ],
      instructions: [
        'Faire revenir oignons et ail.',
        'Ajouter poulet et dorer.',
        'Incorporer tomates.',
        'Diluer palmiste dans bouillon.',
        'Ajouter au poulet.',
        'Laisser mijoter 45 minutes.',
        'Ajouter huile de palme.',
        'Servir avec riz.'
      ],
    ),
    Recipe(
      id: '24',
      title: 'Thieboudienne Sénégalais',
      shortDescription: 'Riz sénégalais au poisson et légumes.',
      fullDescription: 'Le thieboudienne est le plat national sénégalais. Du riz cuit avec du poisson frais, des légumes et des épices dans un bouillon parfumé. Préparation: 30 min | Cuisson: 45 min | Difficulté: Moyenne | Portions: 6',
      imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
      price: 100.0,
      currency: 'CDF',
      likes: 312,
      rating: 4.8,
      ingredients: [
        '400g de riz brisé',
        '1kg de poisson frais',
        '4 tomates',
        '2 oignons',
        '3 gousses d\'ail',
        'Carottes, navets, manioc',
        'Piment, thym, laurier',
        'Huile d\'arachide',
        'Bouillon de poisson',
        'Sel et poivre'
      ],
      instructions: [
        'Faire revenir oignons et ail.',
        'Ajouter légumes et épices.',
        'Incorporer poisson.',
        'Ajouter bouillon.',
        'Laisser mijoter 20 minutes.',
        'Ajouter riz rincé.',
        'Cuire 20 minutes.',
        'Servir immédiatement.'
      ],
    ),
  ];


  Future<List<Recipe>> getRecipes() async {
    // Pour cette démo, retourner les données fictives
    // En production, vous pourriez récupérer depuis Firestore
    return _mockRecipes;
  }

  Future<Recipe?> getRecipeById(String id) async {
    return _mockRecipes.firstWhere((recipe) => recipe.id == id);
  }

  // Méthodes pour gérer les achats (à implémenter avec Firestore)
  Future<void> purchaseRecipe(String userId, String recipeId) async {
    // Logique pour enregistrer l'achat
    await FirebaseFirestore.instance.collection('purchases').add({
      'userId': userId,
      'recipeId': recipeId,
      'purchaseDate': FieldValue.serverTimestamp(),
    });
  }

  Future<List<String>> getPurchasedRecipeIds(String userId) async {
    final snapshot = await FirebaseFirestore.instance
        .collection('purchases')
        .where('userId', isEqualTo: userId)
        .get();
    return snapshot.docs.map((doc) => doc['recipeId'] as String).toList();
  }
}